# 席替えを自動で行うGUIアプリ
# 1. 席の行数、列数を数字で入力し、席数決定ボタンを押す
# 2. 視力等で配慮する席、使用しない席を、指示通りに入力する
# 3. 席替開始ボタンを押すと、数字をランダムに配置して、席替えを完了する
# Windows10, Python 3.12.0で動作確認済み

import tkinter as tk
import random

x_sta = 60
x_interval = 50
y_sta = 120
y_interval = 40

def seat_calc(target):
    k = int(entry1.get())
    v = int(entry2.get())
    h3.place(x = 10+400, y = 10)
    entry3.place(x = 100+400, y = 10)
    entry3.delete(0, tk.END)
    entry3.insert(tk.END, str(k * v))
    button1.place_forget()
    seat_none(k,v)
    seat_start()

def seat_none(l,r):
    if l < 7:
        if l < 6:
            if l < 5:
                if l < 4:
                    if l < 3:
                        if l < 2:
                            p11.delete(0, tk.END)
                            p11.insert(tk.END, 'X')
                            p12.delete(0, tk.END)
                            p12.insert(tk.END, 'X')        
                            p13.delete(0, tk.END)
                            p13.insert(tk.END, 'X')       
                            p14.delete(0, tk.END)
                            p14.insert(tk.END, 'X')       
                            p15.delete(0, tk.END)
                            p15.insert(tk.END, 'X')        
                            p16.delete(0, tk.END)
                            p16.insert(tk.END, 'X')        
                            p17.delete(0, tk.END)
                            p17.insert(tk.END, 'X')        
                            p18.delete(0, tk.END)
                            p18.insert(tk.END, 'X')        
                            p19.delete(0, tk.END)
                            p19.insert(tk.END, 'X')
                            p20.delete(0, tk.END)
                            p20.insert(tk.END, 'X')
                        p21.delete(0, tk.END)
                        p21.insert(tk.END, 'X')
                        p22.delete(0, tk.END)
                        p22.insert(tk.END, 'X')        
                        p23.delete(0, tk.END)
                        p23.insert(tk.END, 'X')       
                        p24.delete(0, tk.END)
                        p24.insert(tk.END, 'X')       
                        p25.delete(0, tk.END)
                        p25.insert(tk.END, 'X')        
                        p26.delete(0, tk.END)
                        p26.insert(tk.END, 'X')        
                        p27.delete(0, tk.END)
                        p27.insert(tk.END, 'X')        
                        p28.delete(0, tk.END)
                        p28.insert(tk.END, 'X')        
                        p29.delete(0, tk.END)
                        p29.insert(tk.END, 'X')
                        p30.delete(0, tk.END)
                        p30.insert(tk.END, 'X')
                    p31.delete(0, tk.END)
                    p31.insert(tk.END, 'X')
                    p32.delete(0, tk.END)
                    p32.insert(tk.END, 'X')        
                    p33.delete(0, tk.END)
                    p33.insert(tk.END, 'X')       
                    p34.delete(0, tk.END)
                    p34.insert(tk.END, 'X')       
                    p35.delete(0, tk.END)
                    p35.insert(tk.END, 'X')        
                    p36.delete(0, tk.END)
                    p36.insert(tk.END, 'X')        
                    p37.delete(0, tk.END)
                    p37.insert(tk.END, 'X')        
                    p38.delete(0, tk.END)
                    p38.insert(tk.END, 'X')        
                    p39.delete(0, tk.END)
                    p39.insert(tk.END, 'X')
                    p40.delete(0, tk.END)
                    p40.insert(tk.END, 'X')
                p41.delete(0, tk.END)
                p41.insert(tk.END, 'X')
                p42.delete(0, tk.END)
                p42.insert(tk.END, 'X')        
                p43.delete(0, tk.END)
                p43.insert(tk.END, 'X')       
                p44.delete(0, tk.END)
                p44.insert(tk.END, 'X')       
                p45.delete(0, tk.END)
                p45.insert(tk.END, 'X')        
                p46.delete(0, tk.END)
                p46.insert(tk.END, 'X')        
                p47.delete(0, tk.END)
                p47.insert(tk.END, 'X')        
                p48.delete(0, tk.END)
                p48.insert(tk.END, 'X')        
                p49.delete(0, tk.END)
                p49.insert(tk.END, 'X')
                p50.delete(0, tk.END)
                p50.insert(tk.END, 'X')
            p51.delete(0, tk.END)
            p51.insert(tk.END, 'X')
            p52.delete(0, tk.END)
            p52.insert(tk.END, 'X')        
            p53.delete(0, tk.END)
            p53.insert(tk.END, 'X')       
            p54.delete(0, tk.END)
            p54.insert(tk.END, 'X')       
            p55.delete(0, tk.END)
            p55.insert(tk.END, 'X')        
            p56.delete(0, tk.END)
            p56.insert(tk.END, 'X')        
            p57.delete(0, tk.END)
            p57.insert(tk.END, 'X')        
            p58.delete(0, tk.END)
            p58.insert(tk.END, 'X')        
            p59.delete(0, tk.END)
            p59.insert(tk.END, 'X')
            p60.delete(0, tk.END)
            p60.insert(tk.END, 'X')
        p61.delete(0, tk.END)
        p61.insert(tk.END, 'X')
        p62.delete(0, tk.END)
        p62.insert(tk.END, 'X')        
        p63.delete(0, tk.END)
        p63.insert(tk.END, 'X')       
        p64.delete(0, tk.END)
        p64.insert(tk.END, 'X')       
        p65.delete(0, tk.END)
        p65.insert(tk.END, 'X')        
        p66.delete(0, tk.END)
        p66.insert(tk.END, 'X')        
        p67.delete(0, tk.END)
        p67.insert(tk.END, 'X')        
        p68.delete(0, tk.END)
        p68.insert(tk.END, 'X')        
        p69.delete(0, tk.END)
        p69.insert(tk.END, 'X')
        p70.delete(0, tk.END)
        p70.insert(tk.END, 'X')

    if r < 10:
        if r < 9:
            if r < 8:
                if r < 7:
                    if r < 6:
                        if r < 5:
                            if r < 4:
                                if r < 3:
                                    if r < 2:
                                        p2.delete(0, tk.END)
                                        p2.insert(tk.END, 'X')
                                        p12.delete(0, tk.END)
                                        p12.insert(tk.END, 'X')
                                        p22.delete(0, tk.END)
                                        p22.insert(tk.END, 'X')
                                        p32.delete(0, tk.END)
                                        p32.insert(tk.END, 'X')
                                        p42.delete(0, tk.END)
                                        p42.insert(tk.END, 'X')
                                        p52.delete(0, tk.END)
                                        p52.insert(tk.END, 'X')
                                        p62.delete(0, tk.END)
                                        p62.insert(tk.END, 'X')
                                    p3.delete(0, tk.END)
                                    p3.insert(tk.END, 'X')
                                    p13.delete(0, tk.END)
                                    p13.insert(tk.END, 'X')
                                    p23.delete(0, tk.END)
                                    p23.insert(tk.END, 'X')
                                    p33.delete(0, tk.END)
                                    p33.insert(tk.END, 'X')
                                    p43.delete(0, tk.END)
                                    p43.insert(tk.END, 'X')
                                    p53.delete(0, tk.END)
                                    p53.insert(tk.END, 'X')
                                    p63.delete(0, tk.END)
                                    p63.insert(tk.END, 'X')
                                p4.delete(0, tk.END)
                                p4.insert(tk.END, 'X')
                                p14.delete(0, tk.END)
                                p14.insert(tk.END, 'X')
                                p24.delete(0, tk.END)
                                p24.insert(tk.END, 'X')
                                p34.delete(0, tk.END)
                                p34.insert(tk.END, 'X')
                                p44.delete(0, tk.END)
                                p44.insert(tk.END, 'X')
                                p54.delete(0, tk.END)
                                p54.insert(tk.END, 'X')
                                p64.delete(0, tk.END)
                                p64.insert(tk.END, 'X')
                            p5.delete(0, tk.END)
                            p5.insert(tk.END, 'X')
                            p15.delete(0, tk.END)
                            p15.insert(tk.END, 'X')
                            p25.delete(0, tk.END)
                            p25.insert(tk.END, 'X')
                            p35.delete(0, tk.END)
                            p35.insert(tk.END, 'X')
                            p45.delete(0, tk.END)
                            p45.insert(tk.END, 'X')
                            p55.delete(0, tk.END)
                            p55.insert(tk.END, 'X')
                            p65.delete(0, tk.END)
                            p65.insert(tk.END, 'X')
                        p6.delete(0, tk.END)
                        p6.insert(tk.END, 'X')
                        p16.delete(0, tk.END)
                        p16.insert(tk.END, 'X')
                        p26.delete(0, tk.END)
                        p26.insert(tk.END, 'X')
                        p36.delete(0, tk.END)
                        p36.insert(tk.END, 'X')
                        p46.delete(0, tk.END)
                        p46.insert(tk.END, 'X')
                        p56.delete(0, tk.END)
                        p56.insert(tk.END, 'X')
                        p66.delete(0, tk.END)
                        p66.insert(tk.END, 'X')
                    p7.delete(0, tk.END)
                    p7.insert(tk.END, 'X')
                    p17.delete(0, tk.END)
                    p17.insert(tk.END, 'X')
                    p27.delete(0, tk.END)
                    p27.insert(tk.END, 'X')
                    p37.delete(0, tk.END)
                    p37.insert(tk.END, 'X')
                    p47.delete(0, tk.END)
                    p47.insert(tk.END, 'X')
                    p57.delete(0, tk.END)
                    p57.insert(tk.END, 'X')
                    p67.delete(0, tk.END)
                    p67.insert(tk.END, 'X')
                p8.delete(0, tk.END)
                p8.insert(tk.END, 'X')
                p18.delete(0, tk.END)
                p18.insert(tk.END, 'X')
                p28.delete(0, tk.END)
                p28.insert(tk.END, 'X')
                p38.delete(0, tk.END)
                p38.insert(tk.END, 'X')
                p48.delete(0, tk.END)
                p48.insert(tk.END, 'X')
                p58.delete(0, tk.END)
                p58.insert(tk.END, 'X')
                p68.delete(0, tk.END)
                p68.insert(tk.END, 'X')
            p9.delete(0, tk.END)
            p9.insert(tk.END, 'X')
            p19.delete(0, tk.END)
            p19.insert(tk.END, 'X')
            p29.delete(0, tk.END)
            p29.insert(tk.END, 'X')
            p39.delete(0, tk.END)
            p39.insert(tk.END, 'X')
            p49.delete(0, tk.END)
            p49.insert(tk.END, 'X')
            p59.delete(0, tk.END)
            p59.insert(tk.END, 'X')
            p69.delete(0, tk.END)
            p69.insert(tk.END, 'X')
        p10.delete(0, tk.END)
        p10.insert(tk.END, 'X')
        p20.delete(0, tk.END)
        p20.insert(tk.END, 'X')
        p30.delete(0, tk.END)
        p30.insert(tk.END, 'X')
        p40.delete(0, tk.END)
        p40.insert(tk.END, 'X')
        p50.delete(0, tk.END)
        p50.insert(tk.END, 'X')
        p60.delete(0, tk.END)
        p60.insert(tk.END, 'X')
        p70.delete(0, tk.END)
        p70.insert(tk.END, 'X')

def seat_start():
    h4.place(x = 70, y = 55)
    h5.place(x = 70, y = 80)
    button2.place(x = x_sta, y = y_sta + y_interval*7)
    button3.place(x = x_sta*4, y = y_sta + y_interval*7)


def seat_dec(target):
    seat_list = [[0 for j in range(10)] for i in range(7)]
    k = int(entry1.get())
    v = int(entry2.get())
    num_list = list(range(k*v))
    random_n = k*v
    seat_list[0][0] = p1.get()
    seat_list[0][1] = p2.get()
    seat_list[0][2] = p3.get()
    seat_list[0][3] = p4.get()
    seat_list[0][4] = p5.get()
    seat_list[0][5] = p6.get()
    seat_list[0][6] = p7.get()
    seat_list[0][7] = p8.get()
    seat_list[0][8] = p9.get()
    seat_list[0][9] = p10.get()
    seat_list[1][0] = p11.get()
    seat_list[1][1] = p12.get()
    seat_list[1][2] = p13.get()
    seat_list[1][3] = p14.get()
    seat_list[1][4] = p15.get()
    seat_list[1][5] = p16.get()
    seat_list[1][6] = p17.get()
    seat_list[1][7] = p18.get()
    seat_list[1][8] = p19.get()
    seat_list[1][9] = p20.get()
    seat_list[2][0] = p21.get()
    seat_list[2][1] = p22.get()
    seat_list[2][2] = p23.get()
    seat_list[2][3] = p24.get()
    seat_list[2][4] = p25.get()
    seat_list[2][5] = p26.get()
    seat_list[2][6] = p27.get()
    seat_list[2][7] = p28.get()
    seat_list[2][8] = p29.get()
    seat_list[2][9] = p30.get()      
    seat_list[3][0] = p31.get()
    seat_list[3][1] = p32.get()
    seat_list[3][2] = p33.get()
    seat_list[3][3] = p34.get()
    seat_list[3][4] = p35.get()
    seat_list[3][5] = p36.get()
    seat_list[3][6] = p37.get()
    seat_list[3][7] = p38.get()
    seat_list[3][8] = p39.get()
    seat_list[3][9] = p40.get()      
    seat_list[4][0] = p41.get()
    seat_list[4][1] = p42.get()
    seat_list[4][2] = p43.get()
    seat_list[4][3] = p44.get()
    seat_list[4][4] = p45.get()
    seat_list[4][5] = p46.get()
    seat_list[4][6] = p47.get()
    seat_list[4][7] = p48.get()
    seat_list[4][8] = p49.get()
    seat_list[4][9] = p50.get()      
    seat_list[5][0] = p51.get()
    seat_list[5][1] = p52.get()
    seat_list[5][2] = p53.get()
    seat_list[5][3] = p54.get()
    seat_list[5][4] = p55.get()
    seat_list[5][5] = p56.get()
    seat_list[5][6] = p57.get()
    seat_list[5][7] = p58.get()
    seat_list[5][8] = p59.get()
    seat_list[5][9] = p60.get()      
    seat_list[6][0] = p61.get()
    seat_list[6][1] = p62.get()
    seat_list[6][2] = p63.get()
    seat_list[6][3] = p64.get()
    seat_list[6][4] = p65.get()
    seat_list[6][5] = p66.get()
    seat_list[6][6] = p67.get()
    seat_list[6][7] = p68.get()
    seat_list[6][8] = p69.get()
    seat_list[6][9] = p70.get()
    for m in range(k):
        for n in range(v):
            # print(f"m:{m},n:{n}")
        # 指定区間内の 空白 or 数字 or 入力ミス、どうする？
        # 数字をちゃんと入れてくれていると仮定する
        # 空白でないとき、その場所を保存する→行列に-1を入力
        # 内容をnum_listから省く
            if seat_list[m][n] != '':
                # print(f"exist m:{m},n:{n}")
                # print(seat_list[m][n])]
                if seat_list[m][n] == '0':
                    num_list.pop(len(num_list)-1)
                else:
                    val = seat_list[m][n]
                    num_list.remove(int(val)-1)
                # print(int(val)-1)

    # num_list に残っているものを、空白のリストに入れていく
    for m in range(k):
        for n in range(v):
            if seat_list[m][n] == '':
                seat_list[m][n] = random.choice(num_list)+1
                num_list.remove(seat_list[m][n]-1)
                # print(int(seat_list[m][n]))

            # num_r = int(seat_list[m,n])
            # num_list.remove(num_r)
            # seat_list[m][n]=1
        # 残ったnum_listから
    p1.delete(0,tk.END)    
    p1.insert(tk.END,str(seat_list[0][0]))
    p2.delete(0,tk.END)    
    p2.insert(tk.END,str(seat_list[0][1]))
    p3.delete(0,tk.END)    
    p3.insert(tk.END,str(seat_list[0][2]))
    p4.delete(0,tk.END)    
    p4.insert(tk.END,str(seat_list[0][3]))
    p5.delete(0,tk.END)    
    p5.insert(tk.END,str(seat_list[0][4]))
    p6.delete(0,tk.END)    
    p6.insert(tk.END,str(seat_list[0][5]))
    p7.delete(0,tk.END)    
    p7.insert(tk.END,str(seat_list[0][6]))
    p8.delete(0,tk.END)    
    p8.insert(tk.END,str(seat_list[0][7]))
    p9.delete(0,tk.END)    
    p9.insert(tk.END,str(seat_list[0][8]))
    p10.delete(0,tk.END)    
    p10.insert(tk.END,str(seat_list[0][9]))
    p11.delete(0,tk.END)    
    p11.insert(tk.END,str(seat_list[1][0]))
    p12.delete(0,tk.END)    
    p12.insert(tk.END,str(seat_list[1][1]))
    p13.delete(0,tk.END)    
    p13.insert(tk.END,str(seat_list[1][2]))
    p14.delete(0,tk.END)    
    p14.insert(tk.END,str(seat_list[1][3]))
    p15.delete(0,tk.END)    
    p15.insert(tk.END,str(seat_list[1][4]))
    p16.delete(0,tk.END)    
    p16.insert(tk.END,str(seat_list[1][5]))
    p17.delete(0,tk.END)    
    p17.insert(tk.END,str(seat_list[1][6]))
    p18.delete(0,tk.END)    
    p18.insert(tk.END,str(seat_list[1][7]))
    p19.delete(0,tk.END)    
    p19.insert(tk.END,str(seat_list[1][8]))
    p20.delete(0,tk.END)    
    p20.insert(tk.END,str(seat_list[1][9]))
    p21.delete(0,tk.END)    
    p21.insert(tk.END,str(seat_list[2][0]))
    p22.delete(0,tk.END)    
    p22.insert(tk.END,str(seat_list[2][1]))
    p23.delete(0,tk.END)    
    p23.insert(tk.END,str(seat_list[2][2]))
    p24.delete(0,tk.END)    
    p24.insert(tk.END,str(seat_list[2][3]))
    p25.delete(0,tk.END)    
    p25.insert(tk.END,str(seat_list[2][4]))
    p26.delete(0,tk.END)    
    p26.insert(tk.END,str(seat_list[2][5]))
    p27.delete(0,tk.END)    
    p27.insert(tk.END,str(seat_list[2][6]))
    p28.delete(0,tk.END)    
    p28.insert(tk.END,str(seat_list[2][7]))
    p29.delete(0,tk.END)    
    p29.insert(tk.END,str(seat_list[2][8]))
    p30.delete(0,tk.END)    
    p30.insert(tk.END,str(seat_list[2][9]))
    p31.delete(0,tk.END)    
    p31.insert(tk.END,str(seat_list[3][0]))
    p32.delete(0,tk.END)    
    p32.insert(tk.END,str(seat_list[3][1]))
    p33.delete(0,tk.END)    
    p33.insert(tk.END,str(seat_list[3][2]))
    p34.delete(0,tk.END)    
    p34.insert(tk.END,str(seat_list[3][3]))
    p35.delete(0,tk.END)    
    p35.insert(tk.END,str(seat_list[3][4]))
    p36.delete(0,tk.END)    
    p36.insert(tk.END,str(seat_list[3][5]))
    p37.delete(0,tk.END)    
    p37.insert(tk.END,str(seat_list[3][6]))
    p38.delete(0,tk.END)    
    p38.insert(tk.END,str(seat_list[3][7]))
    p39.delete(0,tk.END)    
    p39.insert(tk.END,str(seat_list[3][8]))
    p40.delete(0,tk.END)    
    p40.insert(tk.END,str(seat_list[3][9]))
    p41.delete(0,tk.END)    
    p41.insert(tk.END,str(seat_list[4][0]))
    p42.delete(0,tk.END)    
    p42.insert(tk.END,str(seat_list[4][1]))
    p43.delete(0,tk.END)    
    p43.insert(tk.END,str(seat_list[4][2]))
    p44.delete(0,tk.END)    
    p44.insert(tk.END,str(seat_list[4][3]))
    p45.delete(0,tk.END)    
    p45.insert(tk.END,str(seat_list[4][4]))
    p46.delete(0,tk.END)    
    p46.insert(tk.END,str(seat_list[4][5]))
    p47.delete(0,tk.END)    
    p47.insert(tk.END,str(seat_list[4][6]))
    p48.delete(0,tk.END)    
    p48.insert(tk.END,str(seat_list[4][7]))
    p49.delete(0,tk.END)    
    p49.insert(tk.END,str(seat_list[4][8]))
    p50.delete(0,tk.END)    
    p50.insert(tk.END,str(seat_list[4][9]))
    p51.delete(0,tk.END)    
    p51.insert(tk.END,str(seat_list[5][0]))
    p52.delete(0,tk.END)    
    p52.insert(tk.END,str(seat_list[5][1]))
    p53.delete(0,tk.END)    
    p53.insert(tk.END,str(seat_list[5][2]))
    p54.delete(0,tk.END)    
    p54.insert(tk.END,str(seat_list[5][3]))
    p55.delete(0,tk.END)    
    p55.insert(tk.END,str(seat_list[5][4]))
    p56.delete(0,tk.END)    
    p56.insert(tk.END,str(seat_list[5][5]))
    p57.delete(0,tk.END)    
    p57.insert(tk.END,str(seat_list[5][6]))
    p58.delete(0,tk.END)    
    p58.insert(tk.END,str(seat_list[5][7]))
    p59.delete(0,tk.END)    
    p59.insert(tk.END,str(seat_list[5][8]))
    p60.delete(0,tk.END)    
    p60.insert(tk.END,str(seat_list[5][9]))
    p61.delete(0,tk.END)    
    p61.insert(tk.END,str(seat_list[6][0]))
    p62.delete(0,tk.END)    
    p62.insert(tk.END,str(seat_list[6][1]))
    p63.delete(0,tk.END)    
    p63.insert(tk.END,str(seat_list[6][2]))
    p64.delete(0,tk.END)    
    p64.insert(tk.END,str(seat_list[6][3]))
    p65.delete(0,tk.END)    
    p65.insert(tk.END,str(seat_list[6][4]))
    p66.delete(0,tk.END)    
    p66.insert(tk.END,str(seat_list[6][5]))
    p67.delete(0,tk.END)    
    p67.insert(tk.END,str(seat_list[6][6]))
    p68.delete(0,tk.END)    
    p68.insert(tk.END,str(seat_list[6][7]))
    p69.delete(0,tk.END)    
    p69.insert(tk.END,str(seat_list[6][8]))
    p70.delete(0,tk.END)    
    p70.insert(tk.END,str(seat_list[6][9]))

def seat_reset(target):
    p1.delete(0,tk.END)    
    p2.delete(0,tk.END)    
    p3.delete(0,tk.END)    
    p4.delete(0,tk.END)    
    p5.delete(0,tk.END)    
    p6.delete(0,tk.END)    
    p7.delete(0,tk.END)    
    p8.delete(0,tk.END)    
    p9.delete(0,tk.END)    
    p10.delete(0,tk.END)    
    p11.delete(0,tk.END)    
    p12.delete(0,tk.END)    
    p13.delete(0,tk.END)    
    p14.delete(0,tk.END)    
    p15.delete(0,tk.END)    
    p16.delete(0,tk.END)    
    p17.delete(0,tk.END)    
    p18.delete(0,tk.END)    
    p19.delete(0,tk.END)    
    p20.delete(0,tk.END)    
    p21.delete(0,tk.END)    
    p22.delete(0,tk.END)    
    p23.delete(0,tk.END)    
    p24.delete(0,tk.END)    
    p25.delete(0,tk.END)    
    p26.delete(0,tk.END)    
    p27.delete(0,tk.END)    
    p28.delete(0,tk.END)    
    p29.delete(0,tk.END)    
    p30.delete(0,tk.END)    
    p31.delete(0,tk.END)    
    p32.delete(0,tk.END)    
    p33.delete(0,tk.END)    
    p34.delete(0,tk.END)    
    p35.delete(0,tk.END)    
    p36.delete(0,tk.END)    
    p37.delete(0,tk.END)    
    p38.delete(0,tk.END)    
    p39.delete(0,tk.END)    
    p40.delete(0,tk.END)    
    p41.delete(0,tk.END)    
    p42.delete(0,tk.END)    
    p43.delete(0,tk.END)    
    p44.delete(0,tk.END)    
    p45.delete(0,tk.END)    
    p46.delete(0,tk.END)    
    p47.delete(0,tk.END)    
    p48.delete(0,tk.END)    
    p49.delete(0,tk.END)    
    p50.delete(0,tk.END)    
    p51.delete(0,tk.END)    
    p52.delete(0,tk.END)    
    p53.delete(0,tk.END)    
    p54.delete(0,tk.END)    
    p55.delete(0,tk.END)    
    p56.delete(0,tk.END)    
    p57.delete(0,tk.END)    
    p58.delete(0,tk.END)    
    p59.delete(0,tk.END)    
    p60.delete(0,tk.END)    
    p61.delete(0,tk.END)    
    p62.delete(0,tk.END)    
    p63.delete(0,tk.END)    
    p64.delete(0,tk.END)    
    p65.delete(0,tk.END)    
    p66.delete(0,tk.END)    
    p67.delete(0,tk.END)    
    p68.delete(0,tk.END)    
    p69.delete(0,tk.END)    
    p70.delete(0,tk.END) 
    h3.place_forget()
    entry3.place_forget()
    entry3.delete(0,tk.END)
    h4.place_forget()
    h5.place_forget()
    button1.place(x = 300, y = 10)
    button2.place_forget()
    button3.place_forget()

root = tk.Tk()
root.title('席替え_試作')
root.minsize(600,450)

h1 = tk.Label(text='席の行数', font=('UD デジタル 教科書体 NP', 16))
h1.place(x = 10, y = 10)

entry1 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 16))
entry1.place(x = 100, y = 10)

h2 = tk.Label(text='席の列数', font=('UD デジタル 教科書体 NP', 16))
h2.place(x = 10+140, y = 10)

entry2 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 16))
entry2.place(x = 100+140, y = 10)

button1 = tk.Button(text='席数決定', font=('UD デジタル 教科書体 NP', 12))
button1.bind('<Button-1>', seat_calc)
button1.place(x = 300, y = 10)

h3 = tk.Label(text='席の総数', font=('UD デジタル 教科書体 NP', 16))
h3.place_forget()

entry3 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 16))
entry3.place_forget()

h4 = tk.Label(text='視力等で配慮する席に 半角数字を1から順に', font=('UD デジタル 教科書体 NP', 12))
h4.place_forget()

h5 = tk.Label(text='使用しない席に 半角数字の0を 入力せよ', font=('UD デジタル 教科書体 NP', 12))
h5.place_forget()

p1 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p1.place(x = x_sta, y = y_sta)

p2 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p2.place(x = x_sta + x_interval, y = y_sta)

p3 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p3.place(x = x_sta + x_interval * 2, y = y_sta)

p4 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p4.place(x = x_sta + x_interval * 3, y = y_sta)

p5 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p5.place(x = x_sta + x_interval * 4, y = y_sta)

p6 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p6.place(x = x_sta + x_interval * 5, y = y_sta)

p7 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p7.place(x = x_sta + x_interval * 6, y = y_sta)

p8 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p8.place(x = x_sta + x_interval * 7, y = y_sta)

p9 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p9.place(x = x_sta + x_interval * 8, y = y_sta)

p10 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p10.place(x = x_sta + x_interval * 9, y = y_sta)

p11 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p11.place(x = x_sta, y = y_sta + y_interval)

p12 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p12.place(x = x_sta + x_interval, y = y_sta + y_interval)

p13 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p13.place(x = x_sta + x_interval * 2, y = y_sta + y_interval)

p14 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p14.place(x = x_sta + x_interval * 3, y = y_sta + y_interval)

p15 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p15.place(x = x_sta + x_interval * 4, y = y_sta + y_interval)

p16 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p16.place(x = x_sta + x_interval * 5, y = y_sta + y_interval)

p17 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p17.place(x = x_sta + x_interval * 6, y = y_sta + y_interval)

p18 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p18.place(x = x_sta + x_interval * 7, y = y_sta + y_interval)

p19 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p19.place(x = x_sta + x_interval * 8, y = y_sta + y_interval)

p20 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p20.place(x = x_sta + x_interval * 9, y = y_sta + y_interval)

p21 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p21.place(x = x_sta, y = y_sta + y_interval*2)

p22 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p22.place(x = x_sta + x_interval, y = y_sta + y_interval*2)

p23 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p23.place(x = x_sta + x_interval * 2, y = y_sta + y_interval*2)

p24 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p24.place(x = x_sta + x_interval * 3, y = y_sta + y_interval*2)

p25 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p25.place(x = x_sta + x_interval * 4, y = y_sta + y_interval*2)

p26 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p26.place(x = x_sta + x_interval * 5, y = y_sta + y_interval*2)

p27 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p27.place(x = x_sta + x_interval * 6, y = y_sta + y_interval*2)

p28 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p28.place(x = x_sta + x_interval * 7, y = y_sta + y_interval*2)

p29 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p29.place(x = x_sta + x_interval * 8, y = y_sta + y_interval*2)

p30 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p30.place(x = x_sta + x_interval * 9, y = y_sta + y_interval*2)


p31 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p31.place(x = x_sta, y = y_sta + y_interval*3)

p32 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p32.place(x = x_sta + x_interval, y = y_sta + y_interval*3)

p33 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p33.place(x = x_sta + x_interval * 2, y = y_sta + y_interval*3)

p34 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p34.place(x = x_sta + x_interval * 3, y = y_sta + y_interval*3)

p35 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p35.place(x = x_sta + x_interval * 4, y = y_sta + y_interval*3)

p36 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p36.place(x = x_sta + x_interval * 5, y = y_sta + y_interval*3)

p37 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p37.place(x = x_sta + x_interval * 6, y = y_sta + y_interval*3)

p38 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p38.place(x = x_sta + x_interval * 7, y = y_sta + y_interval*3)

p39 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p39.place(x = x_sta + x_interval * 8, y = y_sta + y_interval*3)

p40 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p40.place(x = x_sta + x_interval * 9, y = y_sta + y_interval*3)

p41 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p41.place(x = x_sta, y = y_sta + y_interval*4)

p42 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p42.place(x = x_sta + x_interval, y = y_sta + y_interval*4)

p43 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p43.place(x = x_sta + x_interval * 2, y = y_sta + y_interval*4)

p44 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p44.place(x = x_sta + x_interval * 3, y = y_sta + y_interval*4)

p45 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p45.place(x = x_sta + x_interval * 4, y = y_sta + y_interval*4)

p46 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p46.place(x = x_sta + x_interval * 5, y = y_sta + y_interval*4)

p47 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p47.place(x = x_sta + x_interval * 6, y = y_sta + y_interval*4)

p48 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p48.place(x = x_sta + x_interval * 7, y = y_sta + y_interval*4)

p49 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p49.place(x = x_sta + x_interval * 8, y = y_sta + y_interval*4)

p50 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p50.place(x = x_sta + x_interval * 9, y = y_sta + y_interval*4)

p51 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p51.place(x = x_sta, y = y_sta + y_interval*5)

p52 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p52.place(x = x_sta + x_interval, y = y_sta + y_interval*5)

p53 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p53.place(x = x_sta + x_interval * 2, y = y_sta + y_interval*5)

p54 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p54.place(x = x_sta + x_interval * 3, y = y_sta + y_interval*5)

p55 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p55.place(x = x_sta + x_interval * 4, y = y_sta + y_interval*5)

p56 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p56.place(x = x_sta + x_interval * 5, y = y_sta + y_interval*5)

p57 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p57.place(x = x_sta + x_interval * 6, y = y_sta + y_interval*5)

p58 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p58.place(x = x_sta + x_interval * 7, y = y_sta + y_interval*5)

p59 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p59.place(x = x_sta + x_interval * 8, y = y_sta + y_interval*5)

p60 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p60.place(x = x_sta + x_interval * 9, y = y_sta + y_interval*5)

p61 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p61.place(x = x_sta, y = y_sta + y_interval*6)

p62 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p62.place(x = x_sta + x_interval, y = y_sta + y_interval*6)

p63 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p63.place(x = x_sta + x_interval * 2, y = y_sta + y_interval*6)

p64 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p64.place(x = x_sta + x_interval * 3, y = y_sta + y_interval*6)

p65 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p65.place(x = x_sta + x_interval * 4, y = y_sta + y_interval*6)

p66 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p66.place(x = x_sta + x_interval * 5, y = y_sta + y_interval*6)

p67 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p67.place(x = x_sta + x_interval * 6, y = y_sta + y_interval*6)

p68 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p68.place(x = x_sta + x_interval * 7, y = y_sta + y_interval*6)

p69 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p69.place(x = x_sta + x_interval * 8, y = y_sta + y_interval*6)

p70 = tk.Entry(width=3, font=('UD デジタル 教科書体 NP', 12))
p70.place(x = x_sta + x_interval * 9, y = y_sta + y_interval*6)

button2 = tk.Button(text='席替開始', font=('UD デジタル 教科書体 NP', 14))
button2.bind('<Button-1>', seat_dec)
button2.place_forget()

button3 = tk.Button(text='リセット', font=('UD デジタル 教科書体 NP', 14))
button3.bind('<Button-1>', seat_reset)
button3.place_forget()

root.mainloop()
